### PR TITLE
Make Get/Watch interfaces for nodes/subnets/namespaces consistent

### PR DESCRIPTION
**Pull request by pravisankar**

### CODE REVIEW

**Comment by pravisankar** [comment]
@rajatchopra @danwinship PTAL

**Comment by marun** [comment]
Why is it necessary to return a pointer to a slice, given that a slice is a reference type (i.e. the cost to copy is negligible)?

**Comment by pravisankar** [comment]
Agree, Copy cost is not worth optimizing here but I do prefer Get/Watch API methods on nodes/namespaces/subnets/net-namespaces to be consistent.

**Comment by marun** [comment]
Is there a reason not to fix the other methods instead?

**Comment by pravisankar** [comment]
Yes, that will be better..thanks. I'll update the PR.

**Comment by pravisankar** [comment]
Updated.
GetNodes() interface is fixed as part of this PR: https://github.com/openshift/openshift-sdn/pull/133

**Comment by danwinship** [comment]
LGTM

**Comment by dcbw** [comment]
LGTM

**Pull request merged**
