### PR TITLE
Update to new ListOptions client APIs

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
Needed for https://github.com/openshift/origin/pull/6320/

**Comment by liggitt** [comment]
Likely won't build right until the rebase lands, just opening this for tracking and reference

**Comment by pravisankar** [comment]
LGTM

**Comment by soltysh** [comment]
Once this lands I'd like to bump sdn in origin.

**Comment by dcbw** [comment]
LGTM; we'll wait until the rebase lands.

**Pull request merged**
