### PR TITLE
For multitenant plugin, handle both existing and admin namespaces

### PR DESCRIPTION
**Pull request by pravisankar**
closes: #129

### CODE REVIEW

**Comment by pravisankar** [comment]
@rajatchopra PTAL

**Comment by pravisankar** [comment]
Yes, we should release allocated NetID when writing to etcd fails. This is what happens, when I do copy+paste :) 
Actually, I should make oc.AdminNamespaces instead of oc.adminNamespaces. Intention here is openshift master will have config param that tells which all namespaces should be treated as special/admin namespaces. If the config param is not explicitly set, it will default to ["default"].

**Comment by pravisankar** [comment]
Removing WIP, tested these changes on multi-node vagrant setup.
@rajatchopra @danwinship updated, PTAL

**Comment by rajatchopra** [comment]
Where is the default? Plan to set in origin/osdn code?

**Comment by pravisankar** [comment]
Yes, default is set in origin sdn plugin: https://github.com/openshift/origin/pull/4370

**Pull request merged**
