### PR TITLE
Validate cluster/service network only when there is a config change

### PR DESCRIPTION
**Pull request by pravisankar**

### CODE REVIEW

**Comment by pravisankar** [comment]
@openshift/networking PTAL

**Comment by danwinship** [comment]
LGTM. This is just an efficiency thing, right? There's nothing actually buggy about the existing code?

**Comment by dcbw** [comment]
LGTM to me too; same question as danw though....

**Comment by pravisankar** [comment]
@danwinship @dcbw 
No issues with the existing code. With this change, validateNetworkConfig() is only called in case of cluster network change and is skipped during start/restart of openshift-master service.

**Pull request merged**
