### PR TITLE
IP Failover diagnostic script

### PR DESCRIPTION
**Pull request by pecameron**
As an OpenShift administrator, I want to know when my ipfailover is
causing my network problems.

Extend the nework debug script so that it can determine why keepalived
is not serving an address appropriately. Ideally we work out which
machine the address should be assigned to, then check that only that
machine has the address assigned, and (ideally) ping the address from
other machines to ensure connectivity.

Trello card:
https://trello.com/c/yFco7WvY/268-5-ip-failover-diagnostic-script-demo-supportability-p3-5

Signed-off-by: Phil Cameron pcameron@redhat.com

### CODE REVIEW

**Comment by pecameron** [comment]
@knobunc Here is the ipf debug script. I made a pass through based on teh style guide. PTAL

**Comment by knobunc** [comment]
LGTM [merge]

**Comment by knobunc** [comment]
@pecameron can you add a bit to the troubleshooting guide -- https://docs.openshift.com/enterprise/3.1/admin_guide/sdn_troubleshooting.html

**Comment by pecameron** [comment]
pr 3402 PTAL

**Pull request merged**
