### PR TITLE
Fix qos check in del_ovs_flows()

### PR DESCRIPTION
**Pull request by pravisankar**
Fix for https://bugzilla.redhat.com/show_bug.cgi?id=1320430

### CODE REVIEW

**Comment by pravisankar** [comment]
@openshift/networking PTAL

**Comment by danwinship** [comment]
how exactly does this bug cause the reported behavior?

**Comment by dcbw** [comment]
It could cause the bug by exiting the script early because qos = "[]" and that QOS doesn't exist, so "ovs-vsctl destroy qos []" returns 1.  This fix LGTM, but we should also do:

ovs-vsctl --if-exists destroy qos ${qos}

to be slightly safer.  The 'clear port' is safe becuase it doesn't care if QoS exists or not.

**Comment by pravisankar** [comment]
@dcbw updated

**Pull request merged**
