### PR TITLE
Tolerate error for tun0 redundant route but not for lbr0 route

### PR DESCRIPTION
**Pull request by pravisankar**

### CODE REVIEW

**Comment by pravisankar** [comment]
@danwinship @dcbw PTAL

**Comment by danwinship** [comment]
I think it would be more idiomatic to have delete_local_subnet_route() just return 0 or 1, and then later do

    delete_local_subnet_route lbr0
    delete_local_subnet_route tun0 || true

though then you don't get "Error" vs "Warning" in the log message. And this is all eventually going away and being replaced by go code hopefully anyway so it doesn't really matter.

lgtm

**Comment by pravisankar** [comment]
updated

**Comment by danwinship** [comment]
saying "Error/Warning" is silly. Just pick one or the other and then merge it

**Pull request merged**
