### PR TITLE
Do not throw spurious error msgs in watch network namespaces

### PR DESCRIPTION
**Pull request by pravisankar**
Depends on https://github.com/openshift/openshift-sdn/pull/279

### CODE REVIEW

**Comment by pravisankar** [comment]
@openshift/networking PTAL

**Comment by dcbw** [comment]
LGTM

**Comment by knobunc** [comment]
LGTM too.  @eparis, this needs someone to wave a merge tag over it please.

**Comment by knobunc** [comment]
LGTM

**Pull request merged**
