### PR TITLE
Add Restart=on-failure to unit files

### PR DESCRIPTION
**Pull request by Miciah**
Add `Restart=on-failure` to the unit files for openshift-sdn-master and openshift-sdn-node.

### CODE REVIEW

**Comment by Miciah** [comment]
@sdodson, :+1:?

**Comment by sdodson** [comment]
Perhaps set RestartSec=1s ? By default it's going to sleep only 100ms, if we're trying to guard against openshift-master startup time that may not be long enough. Otherwise :+1:

**Comment by sdodson** [comment]
Also, FWIW, I was looking at adding systemd notify support to openshift. That would allow openshift to signal to systemd when it had finished starting up so that systemd would wait to start dependencies until after that had happened. However, given that these services aren't necessarily located on the same system we should still restart as you're proposing.

**Comment by Miciah** [comment]
Updated.

**Comment by sdodson** [comment]
:+1:

**Comment by mrunalp** [comment]
@Miciah @sdodson thanks.
LGTM

**Pull request merged**
