### PR TITLE
Makes subnets configurable.

### PR DESCRIPTION
**Pull request by mrunalp**
@rajatchopra PTAL

### CODE REVIEW

**Comment by mrunalp** [comment]
Addresses #30

**Comment by brenton** [comment]
Any chance this will be merged within a day or so?

**Comment by rajatchopra** [comment]
@brenton on the way. A rebased version by the evening.

**Comment by brenton** [comment]
Awesome, thanks Rajat!

**Comment by mrunalp** [comment]
Rebased.

**Comment by rajatchopra** [comment]
Hand tested, works.

**Comment by brenton** [comment]
@sdodson, can you build the latest openshift-sdn package today for beta2?

**Pull request merged**
