### PR TITLE
Drop "lbr" mode

### PR DESCRIPTION
**Pull request by danwinship**
Related to #130, this drops support for lbr / running without kubernetes.

Can --skip-setup and --sync go away as well? origin always passes "false" for both

@pravisankar

### CODE REVIEW

**Comment by rajatchopra** [comment]
--skip-setup might be needed in the future but we can always re-introduce it.
--sync should go away as it is an insecure way of operating in a cluster.

**Comment by danwinship** [comment]
Re-pushed with --sync and --skip-setup deprecated. I didn't remove them from StartMaster()/StartNode() to avoid needing to sync an API update with origin.
The travis-ci failure seems to already exist in master... I'll look into that

**Comment by danwinship** [comment]
er, sorry, repushed with gofmt'ing. (I got confused because running "./hack/test.sh" showed errors, but those are errors that are supposed to be printed...)

**Comment by dcbw** [comment]
LGTM though maybe just fix StartNode since we're always passing false,false ?  or was the intent to panic() in one place only?

**Comment by pravisankar** [comment]
can we close this pr?
https://github.com/openshift/openshift-sdn/pull/159 handles lbr/standalone binary cleanup

**Comment by danwinship** [comment]
obsoleted by #159

**Pull request closed without merging**
