### PR TITLE
Rename pod-network sub-command unisolate-projects to make-projects-global

### PR DESCRIPTION
**Pull request by pravisankar**

### CODE REVIEW

**Comment by pravisankar** [comment]
@danwinship @dcbw @eparis PTAL

I'll update the openshift-docs and auto generated docs/bash-completion-scripts in origin

**Comment by eparis** [comment]
[test]

**Comment by pravisankar** [comment]
docs pr: https://github.com/openshift/openshift-docs/pull/1116

**Comment by danwinship** [comment]
lgtm

**Comment by pravisankar** [comment]
origin pr: https://github.com/openshift/origin/pull/5470

**Pull request merged**
