### PR TITLE
Fix broken VnidStartMaster()

### PR DESCRIPTION
**Pull request by pravisankar**

### CODE REVIEW

**Comment by pravisankar** [comment]
@openshift/networking PTAL

**Comment by pravisankar** [comment]
Fixes panic: interface conversion: interface is []api.Namespace, not []string

**Comment by danwinship** [comment]
that code hasn't changed since October... why hasn't this been a problem before?

**Comment by pravisankar** [comment]
Earlier registry.GetNamespaces() returned []string and as part of this refactor https://github.com/openshift/openshift-sdn/pull/270 we started returning []kapi.Namespace and we missed this change during the refactor.

**Comment by knobunc** [comment]
LGTM. @danwinship any complaints?

**Pull request merged**
